version: '3.8'
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code
    command: sh -c "cd app && npm start"
    ports:
      - "3000:3000"
    # ホットリロードを有効化
    environment:
      - CHOKIDAR_USEPOLLING=true
